version: '3'
services:
    web:
        image: nginx:latest
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-runtime
        ports:
            - 80:80
    php-runtime:
        image: php:7.2-fpm
        volumes:
            - ./:/app
    
